name: adb_dart
description: 纯Dart实现的Android Debug Bridge (ADB)协议库 - 完整复刻Kadb功能
version: 1.0.0
homepage: https://github.com/your-username/adb_dart

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    # 基础加密库
    crypto: ^3.0.3

    # RSA加密支持
    pointycastle: ^3.7.3

    # Base64编解码
    convert: ^3.1.1

    # ASN.1解析
    asn1lib: ^1.5.0

    # 异步处理
    async: ^2.11.0

    # 文件和路径操作
    path: ^1.9.0

    # 时间处理
    clock: ^1.1.1

    # 日志记录
    logging: ^1.2.0

    # 字节数据处理
    typed_data: ^1.3.2

    # 网络通信（纯Dart Socket）
    # 不需要额外的网络库，使用Dart内置的Socket

dev_dependencies:
    lints: ^3.0.0
    test: ^1.24.0
