name: adb_dart
description: 纯Dart实现的Android Debug Bridge (ADB)协议库 - 完整复刻Kadb功能
version: 1.0.0
homepage: https://github.com/your-username/adb_dart

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    # 基础加密库
    crypto: ^3.0.3

    # RSA加密支持
    pointycastle: ^4.0.0

    # Base64编解码
    convert: ^3.1.1
 
    x509_plus: ^0.3.3

    # ASN.1解析
    asn1lib: ^1.5.0

    # 异步处理
    async: ^2.11.0 

    # 日志记录
    logging: ^1.2.0
 

dev_dependencies:
    lints: ^3.0.0
    test: ^1.24.0
